<?php
/**
 * Reports Management - RBI Engineering Suite
 */
$pageTitle = 'Reports';
$currentModule = 'reports';
require_once __DIR__ . '/config/app.php';
requireAuth();

$breadcrumbs = [
    ['label' => 'Dashboard', 'url' => BASE_URL . '/dashboard.php'],
    ['label' => 'Reports', 'url' => '#']
];

$db = new Database();

// Fetch active report templates
$templates = $db->query("SELECT * FROM report_templates WHERE is_active = 1 ORDER BY template_name ASC")->fetchAll();

// Fetch recent saved reports
$savedReports = $db->query("
    SELECT sr.*, u.first_name, u.last_name, rt.template_name
    FROM saved_reports sr
    LEFT JOIN users u ON sr.generated_by = u.id
    LEFT JOIN report_templates rt ON sr.template_id = rt.id
    ORDER BY sr.generated_at DESC
    LIMIT 50
")->fetchAll();

require_once INCLUDES_PATH . '/header.php';
require_once INCLUDES_PATH . '/sidebar.php';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h5 class="mb-0"><i class="bi bi-file-earmark-pdf me-2"></i>Reports</h5>
    <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#generateReportModal">
        <i class="bi bi-plus-circle me-1"></i>Generate Report
    </button>
</div>

<ul class="nav nav-tabs mb-3" role="tablist">
    <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#saved-reports"><i class="bi bi-journal-check me-1"></i>Saved Reports</a></li>
    <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#templates"><i class="bi bi-layout-text-window me-1"></i>Report Templates</a></li>
</ul>

<div class="tab-content">
    <!-- Saved Reports Tab -->
    <div class="tab-pane fade show active" id="saved-reports">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="reportsTable" class="table table-hover align-middle" style="width:100%">
                        <thead class="table-light">
                            <tr>
                                <th>Report Name</th>
                                <th>Template</th>
                                <th>Format</th>
                                <th>Generated By</th>
                                <th>Date</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($savedReports)): ?>
                                <tr><td colspan="6" class="text-center text-muted py-4">No saved reports found. Click "Generate Report" to create one.</td></tr>
                            <?php else: ?>
                                <?php foreach ($savedReports as $sr): ?>
                                    <tr>
                                        <td class="fw-semibold"><?= htmlspecialchars($sr['report_name']) ?></td>
                                        <td><?= htmlspecialchars($sr['template_name'] ?? 'Custom') ?></td>
                                        <td><span class="badge bg-secondary"><?= strtoupper($sr['output_format']) ?></span></td>
                                        <td><?= htmlspecialchars(($sr['first_name'] ?? '') . ' ' . ($sr['last_name'] ?? 'System')) ?></td>
                                        <td><?= date('M d, Y H:i', strtotime($sr['generated_at'])) ?></td>
                                        <td class="text-end">
                                            <button class="btn btn-sm btn-outline-primary" data-bs-toggle="tooltip" title="Download"><i class="bi bi-download"></i></button>
                                            <button class="btn btn-sm btn-outline-danger" data-bs-toggle="tooltip" title="Delete"><i class="bi bi-trash"></i></button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Templates Tab -->
    <div class="tab-pane fade" id="templates">
        <div class="row g-3">
            <?php foreach ($templates as $t): ?>
                <div class="col-md-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-start mb-2">
                                <h6 class="card-title fw-bold mb-0"><?= htmlspecialchars($t['template_name']) ?></h6>
                                <span class="badge bg-info"><?= htmlspecialchars(ucwords(str_replace('_', ' ', $t['module']))) ?></span>
                            </div>
                            <p class="card-text small text-muted"><?= htmlspecialchars($t['description']) ?></p>
                        </div>
                        <div class="card-footer bg-transparent border-top-0 pt-0">
                            <button class="btn btn-sm btn-outline-primary w-100" onclick="selectTemplate(<?= $t['id'] ?>)"><i class="bi bi-magic me-1"></i>Use Template</button>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="bi bi-file-earmark-plus me-2"></i>Generate Report</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="<?= BASE_URL ?>/api/reports.php" method="POST">
                <input type="hidden" name="csrf_token" value="<?= e(generateCsrfToken()) ?>">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Report Template</label>
                        <select name="template_id" id="modalTemplateSelect" class="form-select" required>
                            <option value="">Select a template...</option>
                            <?php foreach ($templates as $t): ?>
                                <option value="<?= $t['id'] ?>"><?= htmlspecialchars($t['template_name']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Report Name</label>
                        <input type="text" name="report_name" class="form-control" placeholder="e.g. Q3 Risk Assessment Summary" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Output Format</label>
                        <select name="output_format" class="form-select">
                            <option value="pdf">PDF Document (.pdf)</option>
                            <option value="excel">Excel Spreadsheet (.xlsx)</option>
                            <option value="csv">CSV File (.csv)</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary"><i class="bi bi-check-circle me-1"></i>Generate</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php
$extraJs = '<script>
document.addEventListener("DOMContentLoaded", function() {
    if (typeof $ !== "undefined" && $.fn.DataTable) {
        $("#reportsTable").DataTable({
            pageLength: 25,
            order: [[4, "desc"]],
            language: { search: "Search reports:" }
        });
    }
});

function selectTemplate(id) {
    const modalElement = document.getElementById("generateReportModal");
    const modal = bootstrap.Modal.getInstance(modalElement) || new bootstrap.Modal(modalElement);
    document.getElementById("modalTemplateSelect").value = id;
    modal.show();
}
</script>';
require_once INCLUDES_PATH . '/footer.php';