<?php
/**
 * Report Center - RBI Engineering Suite
 */
$pageTitle = 'Reports';
require_once __DIR__ . '/../config/app.php';
requireAuth();
$breadcrumbs = [
    ['label' => 'Dashboard', 'url' => BASE_URL . '/dashboard.php'],
    ['label' => 'Reports', 'url' => '#']
];
require_once INCLUDES_PATH . '/header.php';
require_once INCLUDES_PATH . '/sidebar.php';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h5 class="mb-0"><i class="bi bi-file-earmark-bar-graph me-2"></i>Report Center</h5>
</div>

<!-- Report Types -->
<div class="row g-3 mb-4">
    <div class="col-lg-4 col-md-6">
        <div class="card h-100 cursor-pointer" data-bs-toggle="modal" data-bs-target="#generateReportModal" style="cursor:pointer" onclick="setReportType('asset_summary')">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-primary bg-opacity-10 text-primary"><i class="bi bi-box-seam"></i></div>
                <div>
                    <h6 class="mb-1">Asset Summary Report</h6>
                    <small class="text-muted">Complete asset registry with design, operational, and condition data</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card h-100" style="cursor:pointer" onclick="setReportType('risk_register')" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-danger bg-opacity-10 text-danger"><i class="bi bi-exclamation-triangle"></i></div>
                <div>
                    <h6 class="mb-1">Risk Register</h6>
                    <small class="text-muted">All risk assessments with POF, COF, risk levels, and rankings</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card h-100" style="cursor:pointer" onclick="setReportType('inspection_due')" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-warning bg-opacity-10 text-warning"><i class="bi bi-calendar-check"></i></div>
                <div>
                    <h6 class="mb-1">Inspection Due List</h6>
                    <small class="text-muted">Upcoming and overdue inspections with assignments and priorities</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card h-100" style="cursor:pointer" onclick="setReportType('dm_summary')" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-info bg-opacity-10 text-info"><i class="bi bi-bug"></i></div>
                <div>
                    <h6 class="mb-1">Damage Mechanism Summary</h6>
                    <small class="text-muted">Active damage mechanisms by asset with susceptibility ratings</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card h-100" style="cursor:pointer" onclick="setReportType('financial_risk')" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-success bg-opacity-10 text-success"><i class="bi bi-currency-dollar"></i></div>
                <div>
                    <h6 class="mb-1">Financial Risk Report</h6>
                    <small class="text-muted">Financial exposure, inspection ROI, and risk-spend analysis</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card h-100" style="cursor:pointer" onclick="setReportType('corrosion')" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <div class="card-body d-flex align-items-center gap-3">
                <div class="kpi-icon bg-secondary bg-opacity-10 text-secondary"><i class="bi bi-graph-down"></i></div>
                <div>
                    <h6 class="mb-1">Corrosion Rate Report</h6>
                    <small class="text-muted">Corrosion tracking, remaining life, and thickness trends</small>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Saved Reports -->
<div class="card">
    <div class="card-header"><i class="bi bi-folder me-2"></i>Saved Reports</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" id="reportsTable">
                <thead>
                    <tr><th>Report Name</th><th>Type</th><th>Generated</th><th>Generated By</th><th>Format</th><th>Actions</th></tr>
                </thead>
                <tbody>
                    <tr><td>Risk Register - Q1 2026</td><td>Risk Register</td><td>Mar 01, 2026</td><td>J. Smith</td><td><span class="badge bg-danger">PDF</span></td><td><button class="btn btn-sm btn-outline-primary"><i class="bi bi-download"></i></button> <button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></td></tr>
                    <tr><td>Asset Summary - All Units</td><td>Asset Summary</td><td>Feb 15, 2026</td><td>S. Jones</td><td><span class="badge bg-success">CSV</span></td><td><button class="btn btn-sm btn-outline-primary"><i class="bi bi-download"></i></button> <button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></td></tr>
                    <tr><td>Inspection Due List - Mar 2026</td><td>Inspection Due</td><td>Mar 01, 2026</td><td>M. Chen</td><td><span class="badge bg-danger">PDF</span></td><td><button class="btn btn-sm btn-outline-primary"><i class="bi bi-download"></i></button> <button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></td></tr>
                    <tr><td>Financial Risk Analysis 2025</td><td>Financial Risk</td><td>Jan 15, 2026</td><td>J. Smith</td><td><span class="badge bg-danger">PDF</span></td><td><button class="btn btn-sm btn-outline-primary"><i class="bi bi-download"></i></button> <button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"><h5 class="modal-title" id="reportModalTitle">Generate Report</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
            <form method="POST">
                <div class="modal-body">
                    <input type="hidden" name="report_type" id="report_type_input">
                    <div class="mb-3"><label class="form-label">Report Name</label><input type="text" name="report_name" class="form-control" id="report_name_input"></div>
                    <div class="row g-3">
                        <div class="col-md-6"><label class="form-label">Date From</label><input type="date" name="date_from" class="form-control" value="2025-01-01"></div>
                        <div class="col-md-6"><label class="form-label">Date To</label><input type="date" name="date_to" class="form-control" value="<?= date('Y-m-d') ?>"></div>
                    </div>
                    <div class="mb-3 mt-3"><label class="form-label">Facility / Unit</label><select name="facility" class="form-select"><option value="">All</option><option>Unit 100</option><option>Unit 200</option><option>Unit 300</option><option>Unit 400</option></select></div>
                    <div class="mb-3"><label class="form-label">Export Format</label><div class="d-flex gap-2"><div class="form-check"><input class="form-check-input" type="radio" name="format" value="pdf" checked id="fmt-pdf"><label class="form-check-label" for="fmt-pdf">PDF</label></div><div class="form-check"><input class="form-check-input" type="radio" name="format" value="csv" id="fmt-csv"><label class="form-check-label" for="fmt-csv">CSV</label></div><div class="form-check"><input class="form-check-input" type="radio" name="format" value="xlsx" id="fmt-xlsx"><label class="form-check-label" for="fmt-xlsx">Excel</label></div></div></div>
                </div>
                <div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary"><i class="bi bi-file-earmark-arrow-down me-1"></i>Generate</button></div>
            </form>
        </div>
    </div>
</div>

<?php
$extraJs = '<script>
function setReportType(type) {
    let names = { asset_summary: "Asset Summary", risk_register: "Risk Register", inspection_due: "Inspection Due List", dm_summary: "Damage Mechanism Summary", financial_risk: "Financial Risk", corrosion: "Corrosion Rate Report" };
    document.getElementById("report_type_input").value = type;
    document.getElementById("report_name_input").value = names[type] + " - " + new Date().toLocaleDateString();
    document.getElementById("reportModalTitle").textContent = "Generate " + names[type];
}
$(document).ready(function(){ $("#reportsTable").DataTable({ pageLength: 10, order: [[2,"desc"]] }); });
</script>';
require_once INCLUDES_PATH . '/footer.php';
